theme: fullwidth
output: ../docs
skip_undocumented: true
separate_global_declarations: true
readme: README.md
module: SwiftCurrent
author_url: https://github.com/wwt/SwiftCurrent
github_url: https://github.com/wwt/SwiftCurrent
sourcekitten_sourcefile: swiftcurrent-docs.json,swiftcurrentuikit-docs.json
author: WWT and Tyler Thompson