name: Version Bump

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "CI" ]
    branches: [ main ]
    types: [ completed ]

jobs:
  version_bump:
    runs-on: macos-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.repository == 'wwt/SwiftCurrent' }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.TYLER_PAT }}
      - name: Bump version in Podspec and Plist
        id: bump_version
        run: bundle exec fastlane patch
      - name: Commit version changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[ci skip] Apply automatic changes"
          tagging_message: "${{ steps.bump_version.outputs.version }}"
          push_options: --force
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v1.7.3
        with:
          configuration: "changelog_configuration.json"
          ignorePreReleases: "false"
          toTag: ${{ steps.bump_version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TYLER_PAT }}
        with:
          tag_name: ${{ steps.bump_version.outputs.version }}
          release_name: Release ${{ steps.bump_version.outputs.version }}
          body: ${{steps.build_changelog.outputs.changelog}}
